name: Security Audit

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    # Run security audit weekly on Mondays at 6 AM UTC
    - cron: '0 6 * * 1'

jobs:
  security_audit:
    name: Security Audit
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable

    - name: Configure Rust cache
      uses: Swatinem/rust-cache@v2
      with:
        # Cache cargo-audit binary separately
        key: cargo-audit
        
    - name: Cache cargo-audit installation
      uses: actions/cache@v4
      id: cache-cargo-audit
      with:
        path: ~/.cargo/bin/cargo-audit
        key: cargo-audit-${{ runner.os }}
        
    - name: Install cargo-audit
      if: steps.cache-cargo-audit.outputs.cache-hit != 'true'
      run: cargo install cargo-audit

    - name: Run security audit
      run: cargo audit

    - name: Run cargo deny check
      uses: EmbarkStudios/cargo-deny-action@v1